language: ruby

rvm:
  - 2.2.0
  - 2.2.4
  - 2.3.0

sudo: true

script:
  - bundle exec rspec spec.rb
  - node_modules/.bin/karma start karma.conf.js --single-run

before_install:
  - ls -R .
  - uname -a
  - which python
  - which python3
  - which ruby
  - export FIREFOX_BIN=`which firefox`
  - sudo apt-get update
  - sudo apt-get install nodejs
  - which phantomjs
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

notifications:
  email:
    recipients:
      - trlearning@mail.ru
      - betterhelper@mail.ru
    on_success: always
    on_failure: always