language: ruby

rvm:
  - 2.2.0
  - 2.2.4
  - 2.3.0

sudo: false

script: "bundle exec rspec spec.rb"

before_install:
  - ls -R .
  - uname -a

notifications:
  email:
    recipients:
      - trlearning@mail.ru
      - betterhelper@mail.ru
    on_success: always
    on_failure: always