language: ruby

rvm:
  - 2.2.0
  - 2.2.4
  - 2.3.0

sudo: false

script:
  - bundle exec rspec spec.rb
  - node_modules/.bin/karma start karma.conf.js --single-run

before_install:
  - ls -R .
  - uname -a
  - curl -sL https://deb.nodesource.com/setup | sudo bash -
  - apt-get install nodejs
  - npm install

notifications:
  email:
    recipients:
      - trlearning@mail.ru
      - betterhelper@mail.ru
    on_success: always
    on_failure: always